card/urls.py
from django.urls import path
from . import views



app_name = 'card'

urlpatterns = [
    path('', views.home, name='home'),
    path('projects/', views.card, name='card'),
    path('projects/<slug:slug>/', views.detail, name='card_detail'),
    path('programmers/', views.programmers, name='programmers'),
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card.urls'))
]

card/models.py
from django.db import models
from django.utils.text import slugify

class Programmers(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    description = models.TextField()
    age = models.IntegerField()
    image = models.ImageField(upload_to='images/', blank=True)
    joined = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return f"{self.name} {self.last_name}"

class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class Projects(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    programmer_name = models.ForeignKey('Programmers', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project_images/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    def __str__(self) -> str:
        return f"{self.title} created by {self.programmer_name}"

card/views.py
from django.shortcuts import render
from . models import Projects, Programmers
from django.shortcuts import get_object_or_404
def card(request):
    project = Projects.objects.all()
    return render(request, 'projects list.html', {"project":project})

def detail(request, slug):
    projects=get_object_or_404(Projects, slug=slug)
    return render(request, 'detail.html',   {'projects':projects})

def programmers(request):
    programmer = Programmers.objects.all()
    return render(request, 'programmers list.html', {"programmer":programmer})
def home(request):
    return render(request, 'index.html')

templates/detail.html
<title>
    {{ projects.title }}
</title>
<h1>{{ projects.title }}</h1>
<hr>
<p>{{ projects.description }}</p>

templates/programmers list.html
<h1>programmer list</h1>
<hr>
<ul>
    {% for programmers in programmer %}
    <li>
        <a>{{ programmers.name }}  {{ programmers.last_name }}</a>
    </li>
    {% endfor %}
</ul>

templates/projects list.html
<title>
    projects list
</title>
<h1>project list</h1>
<hr>
<ul>
    {% for projects in project %}
    <li>
        <a href="{% url 'card:card_detail' projects.slug %}">{{ projects.title }} - {{ projects.programmer_name }}</a>
    </li>
    {% endfor %}
</ul>